---
abstract: 'Basic method declarations with signatures, without source filters'
author:
  - 'Rhesa Rozendaal <rhesa@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200011, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Method-Signatures-Simple
requires:
  Devel::Declare: 0.003001
resources:
  repository: http://github.com/rhesa/method-signatures-simple
version: 1.02
